name: GitHub Classroom Autograding

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  autograding:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run all tests
      run: |
        pytest tests/ -v --tb=short --strict-markers --disable-warnings
    
    - name: Check test coverage
      run: |
        pytest tests/ --cov=models --cov=simulator --cov-report=term-missing --cov-fail-under=70 